### ISSUE TITLE
sudo: theclicker: command not found

### ISSUE THREAD

**Issue by Vilianexe** [konkitoman/autoclicker#2]
i installed using cargo, and put the cargo/bin in the $PATH, when trying the command without sudo it give `permission denied`, but it give `sudo: theclicker: command not found` when trying with sudo

it work when i install using `sudo cargo install`, but only after i login as root (using sudo -i for example) and then run the program, there is a way to run it only putting "sudo" behind?

EDIT:
Operating System: Fedora Linux 38
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.108.0
Qt Version: 5.15.10
Kernel Version: 6.3.12-200.fc38.x86_64 (64-bit)
Graphics Platform: offscreen
Processors: 8 × AMD Ryzen 7 5700U with Radeon Graphics
Memory: 6.6 GiB of RAM
Graphics Processor: AMD Radeon Graphics

and i installed cargo using the fedora package manager(dnf), maybe it's an issue with the way cargo is installed?

**Comment by konkitoman** [comment]
First thing run groups!
## If input group exists
`run sudo usermod -aG` input {your user name}
Then `su` {your user name}
then you will be able to run `theclicker` without sudo

## If input group do not exists
First thing try to run `'su` {your user name}
And if still dozen't work you can run `sudo /home/{your username}/.cargo/bin/theclicker`

**Comment by konkitoman** [comment]
Wait, how you added `~/.cargo/bin` in your path?

**Comment by konkitoman** [comment]
Or the problem with `sudo` is possible to be because in `/etc/sudoers` if you can find 
`Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"`
You should commented like
 `#Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"`

**Comment by Vilianexe** [comment]
> Wait, how you added `~/.cargo/bin` in your PATH?
```
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:$HOME/go/bin:/home/vdaros/.cargo/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$HOME/go/bin:$HOME/.cargo/bin:$PATH"
fi
export PATH
```
> Or the problem with `sudo` is possible to be because in `/etc/sudoers` if you can find `Defaults secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"` You should commented like `#Defaults secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"`
> 
> And the same thing with `Defaults env_reset`

comment the secute_path and env_reset?, so sudo can run commands on every path?

**Comment by Vilianexe** [comment]
well, commenting both worked thank you!

**Comment by konkitoman** [comment]
```
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:$HOME/go/bin:/home/vdaros/.cargo/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$HOME/go/bin:$HOME/.cargo/bin:$PATH"
fi
export PATH
```
In what file is added

**Comment by konkitoman** [comment]
And for path you can used `export PATH=/home/vdaros/.cargo/bin:$PATH`
If you using bash or zsh

**Comment by Vilianexe** [comment]
> In what file is added

i put it in .bash_profile, but the problem was the secure path in sudoers, cargo has a way to install in /bin or other globally path?, so it isn't needed to edit the sudoers file?

**Comment by Vilianexe** [comment]
> And for your path you can used `export PATH=/home/vdaros/.cargo/bin:$PATH` If you are using bash or zsh

true, but it's the way that came default with fedora, so i just added the .cargo/bin there

**Comment by konkitoman** [comment]
I think you cannot install directly to /bin from cargo install, i cannot find anything on this subject
But if you want to have some thing in bin that is installed with cargo you can use after is installed `sudo cp ~/.cargo/bin/{APP_NAME} /bin/`
Cargo dose not install in /bin because i dozen't wants to override something important or itself
When you install some thing with `cargo install` for example `cargo install kalc-kman` i will be installed as `kalc` you can have multiples executabiles per project with different names
So a single project can override sudo, bash, and more executabiles!
