### ISSUE TITLE
feature: Add a jitter option

### ISSUE THREAD

**Issue by donCESAR12345** [konkitoman/autoclicker#6]
Adding a Jitter option to randomize the clicks between the configured cooldown, so for some purposes it looks more humanlike, should be default to 0.

Another more intricate feature could be adding a decay on the speed, so it looks like the "human" is tiring when clicking for long time, but this may be me trying too hard to impersonate humans with the autoclicker hahahaha.

Anyways, the first one is a reasonable feature, second one is more like an idea ;)

**Comment by konkitoman** [comment]
# :warning: The scope of this project, is not to make a human-like auto clicker!
First to make something human-like is really hard!

# First suggestion
Make the mouse relative position to randomly move a little
- For a user will be annoying because your mouse will run from you!
- To calculate something random can be expensive.
- The random amounts will be stored in precomputed table.

# Second suggestion
Make the duration between clicks randomly change a little
- This will not affect the user in any way.
- The random values will be stored in a precomputed table.
 
# Conclusion
- Any of this changes will not block a anti cheat from detecting or preventing the auto clicker!
- The game/app can only pick a physical devices and bypass the windowing system!
- This will increase the complexity of the code base! 

## I will pick the second suggestion because is less annoying for the user!

# :warning:  I will not start to work on this! :warning:
